### ISSUE TITLE
Error for radio button

### ISSUE THREAD

**Issue by JosefKatic** [creativetimofficial/material-bootstrap-wizard#11]
Hello is there a way how to display error when radio button isn't checked i tried to add a line to material-bootstrap-wizard.js but it didn't work.

**Comment by anjucheran** [comment]
Hi! how did you solve this?

**Comment by oijkn** [comment]
Can you tell me how do you resolved this problem, please ? Because I'm in the same case. Thx

**Comment by JosefKatic** [comment]
> Can you tell me how do you resolved this problem, please ? Because I'm in the same case. Thx

Hello, I've resolved this by adding a tooltip to a radio button , setting the same name to all radio buttons in group and in **material-bootstrap-wizard.js** I have added a rule to JS validation
 `rules:{radio: {required: true}}`. Is it the same you were looking for?
