### ISSUE TITLE
How do I reset all aspect of modal wizard on show

### ISSUE THREAD

**Issue by aashrafCL** [creativetimofficial/material-bootstrap-wizard#16]
when the modal popup shows, if the user clicks somewhere outside of the modal window, the modal window goes away. if  the user shows the modal again, it remembers the last data entry and the active tab it was on. What do I need to do so the modal doesnt remember anything and acts as if this is the first time user has clicked on it

**Comment by alexandru-paduraru** [comment]
@aashrafCL thank you for using our product. We just did the design over Bootstrap Wizard: http://vinceg.github.io/twitter-bootstrap-wizard/# . Please check their documentation on how to reset or jump to the first step. Hope this helps.

Best,
Alex
