### ISSUE TITLE
how to upgrade bootstrap 4.0

### ISSUE THREAD

**Issue by neozhu** [creativetimofficial/material-bootstrap-wizard#24]
have upgraded to 4.0  plan?

**Comment by dragosct** [comment]
Hi, @neozhu! Thank you for using our product. Yes, we will migrate this product on BS4 but at this moment I can't tell you exactly the date of the release. Regards, Dragos

**Comment by neozhu** [comment]
I try to migrate to BS 4 , but not successfully. :(

**Comment by neozhu** [comment]
I try migrate
