### ISSUE TITLE
Issue when using Material Wizard with Material Kit

### ISSUE THREAD

**Issue by minikN** [creativetimofficial/material-bootstrap-wizard#3]
Hello, I noticed that some of CSS breaks if you simply use the wizard together with the kit. I downloaded both the wizard and the kit files, and simply added the kit css and js files to the wizard index file in correct order. Here's the whole file:

`
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Material Bootstrap Wizard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="assets/img/favicon.png" />

	
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	
	<link href="assets/css/bootstrap.min.css" rel="stylesheet" />
	<link href="assets/css/material-kit.css" rel="stylesheet" />
	<link href="assets/css/material-bootstrap-wizard.css" rel="stylesheet" />

	
	<link href="assets/css/demo.css" rel="stylesheet" />
</head>

<body>
	<div class="image-container set-full-height" style="background-image: url('assets/img/wizard-book.jpg')">
	    
	    <a href="http://creative-tim.com">
	         <div class="logo-container">
	            <div class="logo">
	                <img src="assets/img/new_logo.png">
	            </div>
	            <div class="brand">
	                Creative Tim
	            </div>
	        </div>
	    </a>

		
		<a href="http://demos.creative-tim.com/material-kit/index.html?ref=material-bootstrap-wizard" class="made-with-mk">
			<div class="brand">MK</div>
			<div class="made-with">Made with <strong>Material Kit</strong></div>
		</a>

	    
	    <div class="container">
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">
		            
		            <div class="wizard-container">
		                <div class="card wizard-card" data-color="red" id="wizard">
		                    <form action="" method="">
		                

		                    	<div class="wizard-header">
		                        	<h3 class="wizard-title">
		                        		Book a Room
		                        	</h3>
									<h5>This information will let us know more about you.</h5>
		                    	</div>
								<div class="wizard-navigation">
									<ul>
			                            <li><a href="#details" data-toggle="tab">Account</a></li>
			                            <li><a href="#captain" data-toggle="tab">Room Type</a></li>
			                            <li><a href="#description" data-toggle="tab">Extra Details</a></li>
			                        </ul>
								</div>

		                        <div class="tab-content">
		                            <div class="tab-pane" id="details">
		                            	<div class="row">
			                            	<div class="col-sm-12">
			                                	<h4 class="info-text"> Let's start with the basic details.</h4>
			                            	</div>
		                                	<div class="col-sm-6">
												<div class="input-group">
													<span class="input-group-addon">
														<i class="material-icons">email</i>
													</span>
													<div class="form-group label-floating">
			                                          	<label class="control-label">Your Email</label>
			                                          	<input name="name" type="text" class="form-control">
			                                        </div>
												</div>

												<div class="input-group">
													<span class="input-group-addon">
														<i class="material-icons">lock_outline</i>
													</span>
													<div class="form-group label-floating">
			                                          	<label class="control-label">Your Password</label>
			                                          	<input name="name2" type="password" class="form-control">
			                                        </div>
												</div>

		                                	</div>
		                                	<div class="col-sm-6">
		                                    	<div class="form-group label-floating">
		                                        	<label class="control-label">Country</label>
	                                        		<select class="form-control">
														<option disabled="" selected=""></option>
	                                                	<option value="Afghanistan"> Afghanistan </option>
	                                                	<option value="Albania"> Albania </option>
	                                                	<option value="Algeria"> Algeria </option>
	                                                	<option value="American Samoa"> American Samoa </option>
	                                                	<option value="Andorra"> Andorra </option>
	                                                	<option value="Angola"> Angola </option>
	                                                	<option value="Anguilla"> Anguilla </option>
	                                                	<option value="Antarctica"> Antarctica </option>
	                                                	<option value="...">...</option>
		                                        	</select>
		                                    	</div>
												<div class="form-group label-floating">
		                                        	<label class="control-label">Daily Budget</label>
	                                        		<select class="form-control">
														<option disabled="" selected=""></option>
	                                                	<option value="Afghanistan"> < $100 </option>
	                                                	<option value="Albania"> $100 - $499 </option>
	                                                	<option value="Algeria"> $499 - $999 </option>
	                                                	<option value="American Samoa"> $999+ </option>
		                                        	</select>
		                                    	</div>
		                                	</div>
		                            	</div>
		                            </div>
		                            <div class="tab-pane" id="captain">
		                                <h4 class="info-text">What type of room would you want? </h4>
		                                <div class="row">
		                                    <div class="col-sm-10 col-sm-offset-1">
		                                        <div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-radio" rel="tooltip" title="This is good if you travel alone.">
		                                                <input type="radio" name="job" value="Design">
		                                                <div class="icon">
		                                                    <i class="material-icons">weekend</i>
		                                                </div>
		                                                <h6>Single</h6>
		                                            </div>
		                                        </div>
		                                        <div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-radio" rel="tooltip" title="Select this room if you're traveling with your family.">
		                                                <input type="radio" name="job" value="Code">
		                                                <div class="icon">
		                                                    <i class="material-icons">home</i>
		                                                </div>
		                                                <h6>Family</h6>
		                                            </div>
		                                        </div>
												<div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-radio" rel="tooltip" title="Select this option if you are coming with your team.">
		                                                <input type="radio" name="job" value="Code">
		                                                <div class="icon">
		                                                    <i class="material-icons">business</i>
		                                                </div>
		                                                <h6>Business</h6>
		                                            </div>
		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="tab-pane" id="description">
		                                <div class="row">
		                                    <h4 class="info-text"> Drop us a small description.</h4>
		                                    <div class="col-sm-6 col-sm-offset-1">
	                                    		<div class="form-group">
		                                            <label>Room description</label>
		                                            <textarea class="form-control" placeholder="" rows="6"></textarea>
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-4">
		                                    	<div class="form-group">
		                                            <label class="control-label">Example</label>
		                                            <p class="description">"The room really nice name is recognized as being a really awesome room. We use it every sunday when we go fishing and we catch a lot. It has some kind of magic shield around it."</p>
		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
	                        	<div class="wizard-footer">
	                            	<div class="pull-right">
	                                    <input type='button' class='btn btn-next btn-fill btn-danger btn-wd' name='next' value='Next' />
	                                    <input type='button' class='btn btn-finish btn-fill btn-danger btn-wd' name='finish' value='Finish' />
	                                </div>
	                                <div class="pull-left">
	                                    <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous' value='Previous' />

										<div class="footer-checkbox">
											<div class="col-sm-12">
											  <div class="checkbox">
												  <label>
													  <input type="checkbox" name="optionsCheckboxes">
												  </label>
												  Subscribe to our newsletter
											  </div>
										  </div>
										</div>
	                                </div>
	                                <div class="clearfix"></div>
	                        	</div>
		                    </form>
		                </div>
		            </div> 
		        </div>
	    	</div> 
		</div> 

	    <div class="footer">
	        <div class="container text-center">
	             Made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Creative Tim</a>. Free download <a href="http://www.creative-tim.com/product/material-bootstrap-wizard">here.</a>
	        </div>
	    </div>
	</div>

</body>
	
	<script src="assets/js/jquery-2.2.4.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/js/jquery.bootstrap.js" type="text/javascript"></script>
	<script src="assets/js/material.min.js" type="text/javascript"></script>

	
	<script src="assets/js/material-kit.js"></script>
	<script src="assets/js/material-bootstrap-wizard.js"></script>

	
	<script src="assets/js/jquery.validate.min.js"></script>
</html>
`

Note: I removed the Material Core functions from jquery.bootstrap.js since they get loaded with material.min.js. Look at the result in latest Chrome version:

![bildschirmfoto 2017-01-19 um 17 48 17](https://cloud.githubusercontent.com/assets/1888338/22116045/863df286-de6f-11e6-9cd0-22ac71c01273.png)

![bildschirmfoto 2017-01-19 um 17 54 17](https://cloud.githubusercontent.com/assets/1888338/22116299/5a4ea070-de70-11e6-844a-a4d27aaa841f.png)

Edit: I don't know why it doesn't parse the code correctly in here, but here is a pastebin: http://laravel.io/bin/aN8q8

**Comment by minikN** [comment]
This is caused by

`@include shadow-big-color($brand-info);`

inside _pills.scss.

It applies to the anchor tags inside of li items.

**Comment by rbarcelos** [comment]
What do we need to fix it? comment the include?

Thanks

**Comment by alexandru-paduraru** [comment]
@minikN @rbarcelos can you please share with us a link with the problem? From Laravel viewer, I can see only the code, not the final result. In this way, I will check and give you a solution. Something on https://jsfiddle.net/ would help.

Best,
Alex

**Comment by minikN** [comment]
I am not at home at the Moment. Give me a couple oft hours and I will describe what's causing the issue and hownI fixed it.

**Comment by minikN** [comment]
@rbarcelos @alexandru-paduraru Alright so the problem is pretty simple to describe. It occurs if you use the Material Wizard and the Material Kit together. In my case, I use the Material Wizard as a modal inside my project, which also uses the Material Kit. So in this scenario, I use both the wizard's css and the kit's css files, and at at least one point, they collide.

In Material Kit, if you use nav pills, an anchor tag (`<a href="#">Link</a>`) gets applied a box-shadow by default ([official documentation](http://demos.creative-tim.com/material-kit/components-documentation.html#navbar-row)):

```
<ul class="nav nav-pills nav-pills-primary" role="tablist">
	<li>
		<a href="#dashboard" role="tab" data-toggle="tab"> **// <-- THIS TAG** 
			<i class="material-icons">dashboard</i>
			Dashboard
		</a>
	</li>
</ul>
```

This is defined in material-kit/_pills.scss in line 31, 44, 57, 70 and 83. It's a block of code that gets repeated for every color (primary, success, warning, ....)

Example:

```
    &.nav-pills-info{
        > li {
            &.active > a{
                &,
                &:focus,
                &:hover{
                    background-color: $brand-info;
                    @include shadow-big-color($brand-info); **// THIS LINE**
                }
            }
        }
    }
```

So moving on to the wizard now, because it uses nav pills as well to build up the navigation, the above described rules get applied as well.

If you inspect your official [wizard demo](http://demos.creative-tim.com/material-bootstrap-wizard/wizard-book-room.html) with chrome dev tools, you can see how you build up the wizard navigation:

```
<div class="wizard-navigation">
  <ul class="nav nav-pills">
    <li class="active"><a href="#details" data-toggle="tab" aria-expanded="true">Account</a></li>
    <li><a href="#captain" data-toggle="tab">Room Type</a></li>
    <li><a href="#description" data-toggle="tab">Extra Details</a></li>
  </ul>
  <div class="moving-tab" style="width: 250px; transform: translate3d(-8px, 0px, 0px); transition:   transform 0s;">Account</div>
</div>
```

As you can see it's the same setup: `ul.nav-pills > li > &:active > a > &:hover`. Because the material kit assets are being used as well, material kit is unintentionally applying the shadow.

I hope this explanation makes clear what's going on. I fixed this issue by applying a block of scss to counter the behaviour. I did not want to alter the source files, hence why I use my own scss file with all my alternations. 

```
.wizard-navigation {
  >.nav-pills{
      > li {
          &.active > a{
              &,
              &:focus,
              &:hover{
                  box-shadow: none;
              }
          }

      }
  } 
}
```

This block of scss ensures the applied shadow by material kit gets removed again, but only if the `ul.nav-pills` is inside a `div.wizard-navigation` to make sure I don't alter the intended nav-pills behaviour across all material kit.

I hope this helps.

**Comment by alexandru-paduraru** [comment]
@minikN wow! That makes sense. 

Congrats for the deep investigation. We will think of a way to fix this, but from what I see now, the best option is the one described by you, in this way the Material Kit is not altered and the problem in the wizard is fixed. So in a future update, we will make sure this will be included :D

Best,
Alex

**Comment by minikN** [comment]
@alexandru-paduraru always happy to help. The stuff you are offering for free is great. Loving it.

**Comment by nworks16** [comment]
What is the correct way to make the wizard after reaching the end return to the first tab? Is there a function to return to the first tab? and show it. using javascript
