### ISSUE TITLE
Problem when using select2 with Material Wizard

### ISSUE THREAD

**Issue by minikN** [creativetimofficial/material-bootstrap-wizard#4]
Hello, I've encountered a problem when using the select2 jQuery plugin inside your form.

Select2 creates another `<li>`-tag. The wizard now get's confused because `refreshAnimation()`, or in more detail `total_steps = $wizard.find('li').length;` counts the `<li>` created by select2 as well, resulting in total_steps being 1 more than actual `<li>`-tags.

`console.log($wizard.find('li'));` in Chrome:

![bildschirmfoto 2017-01-19 um 19 57 55](https://cloud.githubusercontent.com/assets/1888338/22120810/a06415b6-de81-11e6-8e2e-17e09a9089f9.png)

I fixed it by changing
`total_steps = $wizard.find('li').length;`
to
`total_steps = $wizard.find('.wizard-navigation').find('li').length;`

Maybe you want to apply this as well. Cheers.

**Comment by steve94103** [comment]
I second this issue - you see the problem any time you use an '<li>' within the wizard, which includes creative tim's own 'selects'.    Thanks for the fix, solved it for me.
