### ISSUE TITLE
How can I submit the data

### ISSUE THREAD

**Issue by Hujjat** [creativetimofficial/material-bootstrap-wizard#7]
Hi, 

Thanks for your great project :)

I have changed the finished button type to submit and the form method to get. But When I fill the form and submit the data, it sends only the country not other inputs. What's the problem ?

Thank's :)

**Comment by TechiePriyaRanjan** [comment]
Use some server-side programming languages like PHP, ASP.NET to process the form submit. Make sure you're sending the data to the server or database using proper methods. Internet is equipped with tons of data, Just Google it! 🥇 :)

**Comment by alexandru-paduraru** [comment]
@Hujjat what backend language do you use to test that data that it's received? You can also check what data is sent using jQuery like in this example: https://api.jquery.com/submit/

**Comment by Hujjat** [comment]
@alexandru-paduraru thanks for the response.

I use PHP and the problem solved. [issue](https://github.com/creativetimofficial/material-bootstrap-wizard/issues/8)

@TechiePriyaRanjan haha, Sure I used any programming language. And thank's for replying so soon. =D
