### ISSUE TITLE
Radio buttons are not working

### ISSUE THREAD

**Issue by Hujjat** [creativetimofficial/material-bootstrap-wizard#8]
Hi,

When we select the radio buttons and send the data, I is not selecting anything. What's the problem

Thank's :)

**Comment by alexandru-paduraru** [comment]
@Hujjat thank you for using our product. Can you please send us a link to your project or a github repository where we can check the code?

Best,
Alex

**Comment by Hujjat** [comment]
@alexandru-paduraru thank's for help.

 I used the default file that I have downloaded. You can check the wizard-book-room.html. 
When I fill the form, in second tab, I select room type from those radio options, then, when I click the finish button, I is not sending the room type information. Please check it once. 

Thank's :)

**Comment by alexandru-paduraru** [comment]
@Hujjat got it. It seems the checked attribute should be set with property, not with attribute. So even if in the browser it is adding the checked attribute, it is not changing the value of the property from false to true:

1. the line 165: this `$(this).find('[type="radio"]').attr('checked','true');` with `$(this).find('[type="radio"]').prop('checked','true');` 
2. the line 174: this `$(this).find('[type="checkbox"]').attr('checked','true');` with `$(this).find('[type="checkbox"]').prop('checked','true');`

Then everything will be right.

Let us know if everything is fine.

Best,
Alex

**Comment by Hujjat** [comment]
@alexandru-paduraru Thank's a lot. That worked :) 👍

**Comment by mgr9500** [comment]
@alexandru-paduraru  THANK YOU !!!!! 🥇
