### ISSUE TITLE
Issue in moving-tab when tab is hidden

### ISSUE THREAD

**Issue by Ravikumar15081987** [creativetimofficial/material-bootstrap-wizard#9]
Hi Creative Tim,

Thank you for a great plugin, i love all your plugins..

While using your material-bootstrap-wizard i am facing a problem..
i hide one of the tab after wizard initialize
$('.wizard-card').bootstrapWizard('hide', 4);
$('.wizard-card').bootstrapWizard('resetWizard');
but when next button clicked on index 3..the moving-tab displaying the hidden tab name..

Before Hiding Tab
![screenshot-localhost 8080-2017-05-20-06-15-55](https://cloud.githubusercontent.com/assets/23351139/26271487/1c2dbff2-3d24-11e7-98d4-898b37376115.png)

then hidden tab 4 [Previous Institute Details]
![screenshot-localhost 8080-2017-05-20-06-20-21](https://cloud.githubusercontent.com/assets/23351139/26271513/7da7f856-3d24-11e7-9f4a-8204a35182f4.png)

Its Successfully Hidden
But When press Next button on index  3..Ita automatically jumping to next tab.. 
![screenshot-localhost 8080-2017-05-20-06-22-09](https://cloud.githubusercontent.com/assets/23351139/26271532/bb119ef4-3d24-11e7-8fc6-22272719810b.png)

Please give me solution for this

Thank You

**Comment by alexandru-paduraru** [comment]
@Ravikumar15081987 thank you for using our product. Please make sure you call the function `refreshAnimation($wizard, index);` add your wizard instead of `$wizard` and step 0 in the index which is on line 209 after your resetWizard method so it will initialize again the moving active tab. Also, make sure on line 210 you add to the counter only the visible `<li>` tags. Like this: `    total_steps = $wizard.find('li:visible').length;` 

Then everything should work fine.

Best,
Alex

**Comment by Ravikumar15081987** [comment]
Hi Alex,

Thank you for the reply,, i tired your solution.,but its not working..

**Comment by Ravikumar15081987** [comment]
Hi Alex,

Still not get solution for hidden tab Problem..please find the below ode..which i made changes in code along with ur solution, still not working, please give me solution for problem

Major changes made..
$(document).ready(function(){
        $('.wizard-card').bootstrapWizard('hide', 2);
        $('.wizard-card').bootstrapWizard('resetWizard');
}

function refreshAnimation($wizard, index){
        //total_steps = $wizard.find('.nav li').length;
	total_steps = $wizard.find('li:visible').length;
}




material-bootstrap-wizard.js
/* ----------------------------------------- */
$(document).ready(function(){

    $.material.init();

    /*  Activate the tooltips      */
    $('[rel="tooltip"]').tooltip();

    // Code for the Validator
    var $validator = $('.wizard-card form').validate({
		  rules: {
		    firstname: {
		      required: true,
		      minlength: 3
		    },
		    lastname: {
		      required: true,
		      minlength: 3
		    },
		    email: {
		      required: true,
		      minlength: 3,
		    }
        },

        errorPlacement: function(error, element) {
            $(element).parent('div').addClass('has-error');
         }
	});

    // Wizard Initialization
  	$('.wizard-card').bootstrapWizard({
        'tabClass': 'nav nav-pills',
        'nextSelector': '.btn-next',
        'previousSelector': '.btn-previous',

        onNext: function(tab, navigation, index) {
        	
        },

        onInit : function(tab, navigation, index){
            //check number of tabs and fill the entire row
            var $total = navigation.find('li').length;
            var $wizard = navigation.closest('.wizard-card');

            $first_li = navigation.find('li:first-child a').html();
            $moving_div = $('<div class="moving-tab">' + $first_li + '</div>');
            $('.wizard-card .wizard-navigation').append($moving_div);

            refreshAnimation($wizard, index);

            $('.moving-tab').css('transition','transform 0s');
       },

        onTabClick : function(tab, navigation, index){
            var $valid = $('.wizard-card form').valid();

            if(!$valid){
                return false;
            } else{
                return true;
            }
        },

        onTabShow: function(tab, navigation, index) {
            var $total = navigation.find('li').length;
            var $current = index+1;

            var $wizard = navigation.closest('.wizard-card');

            // If it's the last tab then hide the last button and show the finish instead
            if($current >= $total) {
                $($wizard).find('.btn-next').hide();
                $($wizard).find('.btn-finish').show();
            } else {
                $($wizard).find('.btn-next').show();
                $($wizard).find('.btn-finish').hide();
            }

            button_text = navigation.find('li:nth-child(' + $current + ') a').html();

            setTimeout(function(){
                $('.moving-tab').text(button_text);
            }, 150);

            var checkbox = $('.footer-checkbox');

            if( !index == 0 ){
                $(checkbox).css({
                    'opacity':'0',
                    'visibility':'hidden',
                    'position':'absolute'
                });
            } else {
                $(checkbox).css({
                    'opacity':'1',
                    'visibility':'visible'
                });
            }

            refreshAnimation($wizard, index);
        }
  	});


    // Prepare the preview for profile picture
    $("#wizard-picture").change(function(){
        readURL(this);
    });

    $('[data-toggle="wizard-radio"]').click(function(){
        wizard = $(this).closest('.wizard-card');
        wizard.find('[data-toggle="wizard-radio"]').removeClass('active');
        $(this).addClass('active');
        $(wizard).find('[type="radio"]').removeAttr('checked');
        $(this).find('[type="radio"]').attr('checked','true');
    });

    $('[data-toggle="wizard-checkbox"]').click(function(){
        if( $(this).hasClass('active')){
            $(this).removeClass('active');
            $(this).find('[type="checkbox"]').removeAttr('checked');
        } else {
            $(this).addClass('active');
            $(this).find('[type="checkbox"]').attr('checked','true');
        }
    });

    $('.set-full-height').css('height', 'auto');
	
	**$('.wizard-card').bootstrapWizard('hide', 2);
	$('.wizard-card').bootstrapWizard('resetWizard');**

});



 //Function to show image before upload

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$(window).resize(function(){
    $('.wizard-card').each(function(){
        $wizard = $(this);

        index = $wizard.bootstrapWizard('currentIndex');
        refreshAnimation($wizard, index);

        $('.moving-tab').css({
            'transition': 'transform 0s'
        });
    });
});

function refreshAnimation($wizard, index){
    $total = $wizard.find('.nav li').length;
    $li_width = 100/$total;

    

    //total_steps = $wizard.find('.nav li').length;
    total_steps = $wizard.find('li:visible').length;

    move_distance = $wizard.width() / total_steps;
    index_temp = index;
    vertical_level = 0;

    mobile_device = $(document).width() < 600 && $total > 3;

    if(mobile_device){
        move_distance = $wizard.width() / 2;
        index_temp = index % 2;
        $li_width = 50;
    }

    $wizard.find('.nav li').css('width',$li_width + '%');

    step_width = move_distance;
    move_distance = move_distance * index_temp;

    $current = index + 1;

    if($current == 1 || (mobile_device == true && (index % 2 == 0) )){
        move_distance -= 8;
    } else if($current == total_steps || (mobile_device == true && (index % 2 == 1))){
        move_distance += 8;
    }

    if(mobile_device){
        vertical_level = parseInt(index / 2);
        vertical_level = vertical_level * 38;
    }

    $wizard.find('.moving-tab').css('width', step_width);
    $('.moving-tab').css({
        'transform':'translate3d(' + move_distance + 'px, ' + vertical_level +  'px, 0)',
        'transition': 'all 0.5s cubic-bezier(0.29, 1.42, 0.79, 1)'

    });
}

materialDesign = {

    checkScrollForTransparentNavbar: debounce(function() {
                if($(document).scrollTop() > 260 ) {
                    if(transparent) {
                        transparent = false;
                        $('.navbar-color-on-scroll').removeClass('navbar-transparent');
                    }
                } else {
                    if( !transparent ) {
                        transparent = true;
                        $('.navbar-color-on-scroll').addClass('navbar-transparent');
                    }
                }
        }, 17)

}

function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		clearTimeout(timeout);
		timeout = setTimeout(function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		}, wait);
		if (immediate && !timeout) func.apply(context, args);
	};
};

**Comment by poornamurugesh** [comment]
I too face the same issue. Itried this way it worked out.
when we go for show/hide tabs. material.-bootstrap-wizard.js as well as jquery.bootstrap also has to be modified for Next/Previous tab function.
material.bootstrap.js changes:
 onInit : function(tab, navigation, index){
            //check number of tabs and fill the entire row
           // var $total = navigation.find('li:visible').length;
            var $total = navigation.find('_li:visible_').filter(function() {
                return $(this).css('display') !== 'none';
            }).length;
            
            var $wizard = navigation.closest('.wizard-card');
            
            $first_li = navigation.find('li:first-child a').html();
            $moving_div = $('<div class="moving-tab">' + $first_li + '</div>');
            $('.wizard-card .wizard-navigation').append($moving_div);
            refreshAnimation($wizard, index);
            $('.moving-tab').css('transition','transform 0s');
       },

   //modified 
 onNext: function(tab, navigation, index) {
        	if(!$(tab).next().is(":visible")){
        	if($(tab).next().next().is(":visible")){
        	index = $(tab).next().next().index();	
        	}
        	}
        	var $valid = $('.wizard-card form').valid();
        	if(!$valid) {
        		$validator.focusInvalid();
        		return false;
        	}
        	else{
        		return index;
        	}
        	
        },
      //added below code
        onPrevious:function(tab, navigation, index) {
        	
        	if(!$(tab).prev().is(":visible")){
            	if($(tab).prev().prev().is(":visible")){
            	index = $(tab).prev().prev().index();	
            	}
            }
        	return index;
            	
        },
and in jquery.bootstrap.js
	this.next = function(e) {

		// If we clicked the last then dont activate this
		if(element.hasClass('last')) {
			return false;
		}

		if($settings.onNext && typeof $settings.onNext === 'function' && $settings.onNext($activeTab, $navigation, obj.nextIndex())===false){
			return false;
		}
		/**Modified by Poorna for tab hidden/show for ML Training Component **/
		// Did we click the last button
		//$index = obj.nextIndex();
		var getNextItem = $settings.onNext($activeTab, $navigation, obj.nextIndex());
		$index = getNextItem;
		/** Ends **/
		
		if($index > obj.navigationLength()) {
		} else {
			$navigation.find(baseItemSelector + ':eq('+$index+') a').tab('show');
		}
	};

	this.previous = function(e) {

		// If we clicked the first then dont activate this
		if(element.hasClass('first')) {
			return false;
		}

		if($settings.onPrevious && typeof $settings.onPrevious === 'function' && $settings.onPrevious($activeTab, $navigation, obj.previousIndex())===false){
			return false;
		}
		/**Modified by Poorna for tab hidden/show for ML Training Component **/	
	//	$index = obj.previousIndex();
		if($index < 0) {
		} else {
			var getPrevItem = $settings.onPrevious($activeTab, $navigation, obj.previousIndex());
			$index = getPrevItem;
			$navigation.find(baseItemSelector + ':eq('+$index+') a').tab('show');
		}
		/**Change Ends**/	
	};
